version: '3.4'

services:
  backendengineerinterviewforcandidates:
    image: backendengineerinterviewforcandidates
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 1550:1550
